site_name: "ACS6121 Labs"
site_url: https://lincaolab.github.io/acs6121/
site_description: Lab material for the ACS6121 Course at The University of Sheffield. 
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  font: false
    # text: Source Sans Pro
    # code: Source Code Pro
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: assets/tuos.png
  favicon: assets/favicon.png

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.annotate
  
# copyright: Copyright &copy; 2023 The University of Sheffield
# repo_url: https://github.com/lincaolab/acs6121
# repo_name: lincaolab/acs6121

plugins:
    - search
    - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - footnotes

extra_css:
  - stylesheets/extra.css

# extra:
#   consent:
#     title: Cookie consent
#     description: 
#       We use cookies to recognize your repeated visits and preferences, as well
#       as to measure the effectiveness of our documentation and whether users
#       find what they're searching for. With your consent, you're helping us to
#       make our documentation better.
